### ISSUE TITLE
Eclipse che Dashboard issue (devworkspacetemplates and devworkspace 401 ) 

### ISSUE THREAD

**Issue by rakeshreddyrg09** [eclipse-che/che-operator#1405]
Hi All,
I am installing eclipse che on my k3d k8s cluster using helm chart next version.
Install is Successful and able to hit the dashboard URL, but once the oidc authentication is verified and the callback is also successful but I am getting below error 
**_Failed to fetch available workspaces, reason: Failed to fetch the list of devWorkspaces. Unable to list devworkspaces: unauthorized_**

here is my CheCluster manifest

I am using NFS as my storage class.
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
  namespace: eclipse-che
spec:
  auth:
    externalIdentityProvider: true
    openShiftoAuth: false
    identityProviderURL: "https://test.eu.auth0.com/"   ##  changed for security reasons
    oAuthClientName: "abc"   ##  changed for security reasons
    oAuthSecret: "xyz"   ##  changed for security reasons
  database:
    chePostgresDb: ""
    chePostgresHostName: ""
    chePostgresPort: ""
    chePostgresSecret: ""
    externalDb: false
  devWorkspace:
    enable: true
  k8s:
    ingressClass: kong  ## changed for security reasons
    ingressDomain: "eclipse-che.test-sample.com"    ##  changed for security reasons
    tlsSecretName: che-tls
  metrics:
    enable: true
  server:
    customCheProperties:
      CHE_OIDC_USERNAME__CLAIM: "email"
    cheClusterRoles: ""
    tlsSupport: true
    # cheLogLevel: "DEBUG"
    cheWorkspaceClusterRole: ""
    gitSelfSignedCert: false
    nonProxyHosts: ""
    proxyPort: ""
    proxySecret: ""
    proxyURL: ""
    workspaceNamespaceDefault: <username>-che
  storage:
    postgresPVCStorageClassName: "nfs"
    preCreateSubPaths: true
    pvcClaimSize: 10Gi
    pvcStrategy: common
    workspacePVCStorageClassName: "nfs"
```
here is the browser logs screenshot
![che-error](https://user-images.githubusercontent.com/48629246/174060561-3f71cecc-66ec-4c4b-88b9-528280d8ce32.png)

![chedashboard](https://user-images.githubusercontent.com/48629246/174063096-cafb441f-016e-42f0-b430-0efeaf8469f7.png)

Also I have updated self-signed-certificate into my browser.

Can anyone help me out here.
Thank you.
