### ISSUE TITLE
CheCluster with disableTLS: true still attempts TLS validation on Port 443

### ISSUE THREAD

**Issue by Aramorth** [eclipse-che/che-operator#2009]
## Titel

**CheCluster with `disableTLS: true` still attempts TLS validation on Port 443**

---

## 🧩 Beschreibung

Ich versuche, Eclipse Che auf einem lokalen Kubernetes-Cluster (Docker Desktop unter Windows 11) bereitzustellen. 
Die Che-Instanz läuft unter der Domain `che.192.168.178.xx.nip.io`, welche per CoreDNS im Cluster korrekt aufgelöst wird. 
Die Konfiguration des `CheCluster`-CRDs enthält:

- `disableTLS: true` im `cheServer`
- Annotation: `che.eclipse.org/self-signed-certificate: "false"`

Trotzdem versucht der Operator weiterhin, die Domain via **HTTPS auf Port 443** zu erreichen, und schlägt fehl mit:

```text
Get "https://che.192.168.178.XX.nip.io": dial tcp 192.168.178.xx:443: connect: connection refused
```

In der Folge bleiben alle Komponenten außer dem Operator inaktiv (`che-server`, `plugin-registry`, etc.).

---

## ➀ Reproduktionsschritte

1. Cluster mit Docker Desktop aufsetzen, CoreDNS konfiguriert zur Auflösung von `nip.io`
2. Domain `che.192.168.178.XX.nip.io` über Ingress verfügbar (Port 80)
3. `CheCluster` anwenden mit:

```yaml
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: che-cluster
  namespace: eclipse-che
  annotations:
    che.eclipse.org/self-signed-certificate: "false"
spec:
  networking:
    domain: che.192.168.178.XX.nip.io
  components:
    cheServer:
      disableTLS: true
```

4. Ingress erscheint, keine weiteren Pods
5. Operator-Log enthält wiederholt:

```text
dial tcp 192.168.178.XX:443: connect: connection refused
```

---

## ✅ Erwartetes Verhalten

- Operator erkennt `disableTLS: true` korrekt
- TLS-Prüfung entfällt vollständig
- `che-server` und Co. starten via Port 80

---

## ️ Hinweise

- CoreDNS wurde gepatcht, Domain-Auflösung innerhalb des Clusters funktioniert einwandfrei
- Kein TLS-Terminierung auf Host oder Ingress
- Annotation `self-signed-certificate: false` scheint ignoriert zu werden
- Betroffen: lokale Entwicklungsszenarien ohne TLS-Infrastruktur

---

Vielen Dank im Voraus
